=== Gonzalo10ab/Lenguajes2024_Gonzalo_Martinez_de_la_Torre/segundotrimestre/dtd/ejercicio7.dtd
<!ELEMENT configuracion (informacion, base_datos, usuario, parametros)>
<!ELEMENT informacion (nombre, version, autor)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT base_datos (host, puerto, usuario_bd, contrasena, nombre_bd)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT puerto (#PCDATA)>
<!ELEMENT usuario_bd (#PCDATA)>
<!ELEMENT contrasena (#PCDATA)>
<!ELEMENT nombre_bd (#PCDATA)>
<!ELEMENT usuario (tema, idioma, preferencias)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT preferencias (#PCDATA)>
<!ELEMENT parametros (clave?, valor?)>
<!ELEMENT clave (#PCDATA)>
<!ELEMENT valor (#PCDATA)>

<!ATTLIST configuracion id ID #REQUIRED>

=== Gonzalo10ab/Lenguajes2024_Gonzalo_Martinez_de_la_Torre/segundotrimestre/xml/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuracion SYSTEM "../dtd/ejercicio7.dtd">
<configuracion id="C001">
    <informacion>
        <nombre>Medac</nombre>
        <version>1.2.3</version>
        <autor>Desarrollador X</autor>
    </informacion>
    <base_datos>
        <host>localhost</host>
        <puerto>3306</puerto>
        <usuario_bd>admin</usuario_bd>
        <contrasena>1234</contrasena>
        <nombre_bd>app_db</nombre_bd>
    </base_datos>
    <usuario>
        <tema>oscuro</tema>
        <idioma>es</idioma>
        <preferencias>activado</preferencias>
    </usuario>
    <parametros>
        <clave>tiempo_espera</clave>
        <valor>30</valor>
    </parametros>
</configuracion>
