=== Gonzalo10ab/Lenguajes2024_Gonzalo_Martinez_de_la_Torre/segundotrimestre/dtd/ejercicio6.dtd
<!ELEMENT ficha_vehiculo (marca, modelo, ano, matricula, tipo_combustible, potencia, propietario)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT tipo_combustible (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT propietario (nombre, apellidos, dni)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni (#PCDATA)>

<!ATTLIST ficha_vehiculo id ID #REQUIRED>

=== Gonzalo10ab/Lenguajes2024_Gonzalo_Martinez_de_la_Torre/segundotrimestre/xml/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ficha_vehiculo SYSTEM "../dtd/ejercicio6.dtd">
<ficha_vehiculo id="V001">
    <marca>Toyota</marca>
    <modelo>Corolla</modelo>
    <ano>2020</ano>
    <matricula>1234-ABC</matricula>
    <tipo_combustible>Gasolina</tipo_combustible>
    <potencia>122 CV</potencia>
    <propietario>
        <nombre>Gonzalo</nombre>
        <apellidos>Messi Lionel</apellidos>
        <dni>56789012X</dni>
    </propietario>
</ficha_vehiculo>
