=== Gonzalo10ab/Lenguajes2024_Gonzalo_Martinez_de_la_Torre/segundotrimestre/dtd/ejercicio4.dtd
<!ELEMENT dni (numero, nombre, apellidos, fecha_nacimiento, lugar_nacimiento, nacionalidad, sexo, direccion, fecha_expedicion, fecha_caducidad, equipo_emisor)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT lugar_nacimiento (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT fecha_expedicion (#PCDATA)>
<!ELEMENT fecha_caducidad (#PCDATA)>
<!ELEMENT equipo_emisor (#PCDATA)>

<!ATTLIST dni id ID #REQUIRED>

=== Gonzalo10ab/Lenguajes2024_Gonzalo_Martinez_de_la_Torre/segundotrimestre/xml/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dni SYSTEM "../dtd/ejercicio4.dtd">
<dni id="D001">
    <numero>12345678X</numero>
    <nombre>Zacarias</nombre>
    <apellidos>Flores del Campo</apellidos>
    <fecha_nacimiento>15-07-1990</fecha_nacimiento>
    <lugar_nacimiento>París</lugar_nacimiento>
    <nacionalidad>Española</nacionalidad>
    <sexo>M</sexo>
    <direccion>
        <calle>Nose que poner 21</calle>
        <ciudad>Suiza</ciudad>
        <codigo_postal>28013</codigo_postal>
        <provincia>Madrid</provincia>
    </direccion>
    <fecha_expedicion>10-05-2020</fecha_expedicion>
    <fecha_caducidad>10-05-2030</fecha_caducidad>
    <equipo_emisor>01234567</equipo_emisor>
</dni>
